swagger: '2.0'
info:
  title: Backend
  version: '1.0'
  description: Backend
host: 'localhost:5000'
schemes:
  - http
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - text/plain
produces:
  - application/json
paths:
  $ref: paths.yaml
responses:
  $ref: responses.yaml

